name: ArcadiaCore
main: net.arcadia.ArcadiaCore
version: 1.1.4
api-version: 1.13
author: Kidzyy
description: The backbone of Arcadia.
depend: [LuckPerms, Vault]

commands:
  help:
    description: Main help command.
    aliases: [?, hlp]
  tags:
    description: Change colored player tags.
    aliases: [ctags, tag, tgs]
  mute:
    description: Mute a player, group, or world for a certain amount of time.
    aliases: [mts, mutes]
  random-teleport:
    description: Teleport to a random location.
    aliases: [rtp, randomtp, rteleport]
  commandspy:
    description: Spy on commands from the server.
    aliases: [cmdspy, spycmd, spycommand]
  report:
    description: Report a player for cheating or bad behavior.
    aliases: [rpt, reports]
  bugreport:
    description: Report a bug to server administrators.
    aliases: [bugreport, breport, bugr]
  ping:
    description: Display your current ping to the server.
    aliases: [myping, whatsmyping]
  mvp:
    description: Open up the MVP comsetic menu.
    aliases: [mvpmenu, cosmmvp]
  vip:
    description: Open up the VIP comsetic menu.
    aliases: [vipmenu, cosmvip]
  msg:
    description: Message a player.
    aliases: [message]
  tpa:
    description: Teleport to a player.
    alises: [tpaccept, tprequest]
  reply:
    description: Reply to a message.
    aliases: [r]
  home:
    description: Teleport to, create, and delete home locations.
  nick:
    description: Change your display name.
  info:
    description: Get info about a player, off or online.
    aliases: [whois]
  spawn:
    description: Teleport or set the global spawn.
  gm:
    description: Change your gamemode.
    aliases: [gamemode]
  gma:
    description: Change your gamemode to adventure.
  gmc:
    description: Change your gamemode to creative.
  gms:
    description: Change your gamemode to survival.
  gmsp:
    description: Change your gamemode to spectator.
  heal:
    description: Heal yourself or a player.
  feed:
    description: Feed yourself or a player.
  balance:
    description: View your bank balance.
    aliases: [bal, viewbal, wallet]
  balanceedit:
    description: Edit yours or another player's balance.
    aliases: [editbal, baledit, walletedit, editwallet]
  pay:
    description: Pay a player.
  createkit:
    description: Create a kit.
    aliases: [addkit, makekit]
  deletekit:
    description: Delete a kit.
    aliases: [delkit, remkit]
  kit:
    description: List or select a it.
  permlist:
    description: List permissions of a certain group.
  perm:
    description: Modify permissions of a group.
  createshop:
    description: Create a shop.
    aliases: [mkshop, cshop]
  deleteshop:
    description: Delete a shop.
    aliases: [delshop, dshop]
  smite:
    description: Smite a player.
  tphere:
    description: Teleport a player to yourself.
    aliases: [tph]
  serverinfo:
    description: See a list of server statistics.
    aliases: [sinfo, serveri]
  firework:
    description: Launch a random firework!
    aliases: [fw, firew, fwork]
  givecustomitem:
    description: Receive a custom item.
    aliases: [gci, giveci, gcitem]